<?xml version="1.0"?>
<robot name="simple_rover" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Simple differential-drive rover: base + two drive wheels + rear caster -->

  <!-- Parameters -->
  <xacro:property name="wheel_radius" value="0.06"/>
  <xacro:property name="wheel_width" value="0.02"/>
  <xacro:property name="base_length" value="0.4"/>
  <xacro:property name="base_width" value="0.28"/>
  <xacro:property name="base_height" value="0.08"/>
  <xacro:property name="base_mass" value="5.0"/>
  <xacro:property name="wheel_mass" value="0.5"/>
  <xacro:property name="caster_radius" value="0.03"/>
  <xacro:property name="caster_mass" value="0.1"/>

  <!-- Base link -->
  <link name="base_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${base_mass}"/>
      <!-- Approximate inertia for a rectangular box -->
      <inertia ixx="${(1.0/12.0)*base_mass*(base_height*base_height + base_length*base_length)}" 
               ixy="0" ixz="0"
               iyy="${(1.0/12.0)*base_mass*(base_width*base_width + base_length*base_length)}" iyz="0"
               izz="${(1.0/12.0)*base_mass*(base_width*base_width + base_height*base_height)}"/>
    </inertial>
    <visual>
      <origin xyz="0 0 ${base_height/2.0}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="gray"><color rgba="0.6 0.6 0.6 1.0"/></material>
    </visual>
    <collision>
      <origin xyz="0 0 ${base_height/2.0}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
  </link>

  <!-- Wheels -->
  <!-- Positions: front-left, front-right (x forward, y left positive, z up) -->
  <link name="left_wheel">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${wheel_mass}"/>
      <!-- cylinder approx inertia about center for axis = y -->
      <inertia ixx="${0.5*wheel_mass*wheel_radius*wheel_radius}" ixy="0" ixz="0"
               iyy="${(1.0/12.0)*wheel_mass*(2*wheel_radius*2*wheel_radius + wheel_width*wheel_width)}" iyz="0"
               izz="${0.5*wheel_mass*wheel_radius*wheel_radius}"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <material name="black"><color rgba="0 0 0 1.0"/></material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
  </link>

  <link name="right_wheel">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${wheel_mass}"/>
      <inertia ixx="${0.5*wheel_mass*wheel_radius*wheel_radius}" ixy="0" ixz="0"
               iyy="${(1.0/12.0)*wheel_mass*(2*wheel_radius*2*wheel_radius + wheel_width*wheel_width)}" iyz="0"
               izz="${0.5*wheel_mass*wheel_radius*wheel_radius}"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <material name="black"><color rgba="0 0 0 1.0"/></material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
  </link>

  <!-- Rear caster (simple small wheel, fixed orientation) -->
  <link name="caster_wheel">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${caster_mass}"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
      <material name="dark"><color rgba="0.2 0.2 0.2 1.0"/></material>
    </visual>
  </link>

  <!-- Wheel joints -->
  <!-- Wheel centers are placed near the lower edges of the base -->
  <joint name="left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_wheel"/>
    <!-- place at left side, slightly forward -->
    <origin xyz="${base_length*0.2} ${base_width/2.0 + wheel_width/2.0} ${wheel_radius}" rpy="0 0 0"/>
    <!-- rotate about robot Y axis to spin the wheel -->
    <axis xyz="0 1 0"/>
  </joint>

  <joint name="right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_wheel"/>
    <origin xyz="${base_length*0.2} ${-(base_width/2.0 + wheel_width/2.0)} ${wheel_radius}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- Caster fixed to the rear center of base -->
  <joint name="caster_joint" type="fixed">
    <parent link="base_link"/>
    <child link="caster_wheel"/>
    <origin xyz="${-base_length*0.35} 0 ${caster_radius}" rpy="0 0 0"/>
  </joint>

  <!-- Basic sensors or frames to attach sensors to -->
  <link name="imu_link"/>
  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0 0 ${base_height + 0.02}" rpy="0 0 0"/>
  </joint>

  <!-- Simple tags to make simulation easy -->
  <gazebo reference="left_wheel">
    <mu1>0.0</mu1>
    <mu2>0.0</mu2>
  </gazebo>

</robot>
