services:
  open-webui:
    build:
      context: .
      dockerfile: Dockerfile
    image: open-webui-custom:latest
    container_name: open-webui
    ports:
      - "3000:8080"
    extra_hosts:
      # This allows the container to easily talk to the host machine on Linux
      - "host.docker.internal:host-gateway"
    volumes:
      - open-webui_data:/app/backend/data

volumes:
  open-webui_data: